db:
  image: 'redis:latest'
  restart: always
  tags:
    - databases
  target_num_containers: 2
web:
  image: 'thecodeassassin/tech-test:latest'
  environment:
    - ALLOW_OVERRIDE=True
  links:
    - db
  ports:
    - '8000:80'
  restart: always
  tags:
    - stateless
  target_num_containers: 2